# Generated by Django 4.2.28 on 2026-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='familia',
            field=models.CharField(choices=[('cuerda', 'Cuerda'), ('viento', 'Viento'), ('percusion', 'Percusión'), ('teclado', 'Teclado')], default='cuerda', max_length=100),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('acustico', 'Acústico'), ('electrico', 'Eléctrico'), ('digital', 'Digital')], default='acustico', max_length=100),
        ),
    ]
